development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bookmeetup.mailer
  :password: gleniscool
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: bookmeetup.mailer
  :password: gleniscool
  :enable_starttls_auto: true